version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- pwsh: >-
    git checkout $env:APPVEYOR_REPO_BRANCH -q

    choco install docfx -y

    docfx docfx.json

artifacts:
- path: _site
  name: _site
deploy:
- provider: Environment
  name: WebSite