variables:
  azure.subscription: 'DataScenarios'
resources:
- repo: self
trigger:
- master
queue:
  name: Hosted VS2017
steps:
- powershell: |
    $(Build.Repository.LocalPath)\prebuild.ps1
  displayName: 'Prebuild actions'
- powershell: |
   choco install docfx -y
   docfx docfx.json 
  displayName: 'Build Documentation'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\site'
    TargetFolder: '$(Build.Repository.LocalPath)\_site'
  displayName: 'Copy Files to: $(Build.Repository.LocalPath)\_site'
- powershell: |
    $(Build.Repository.LocalPath)\postbuild.ps1
  displayName: 'Postbuild actions'
- task: AzureCLI@2
  displayName: 'sync storage static website'
  inputs:
    azureSubscription: '$(azure.subscription)'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'az storage blob sync -c $web --account-name azuredocsdatascenarios -s "_site"'
- task: AzureCLI@2
  displayName: "purge CDN endpoints due to refresh content"
  inputs:
      azureSubscription: "$(azure.subscription)"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: 'az cdn endpoint purge -g websites -n azuredocsdatascenarios --profile-name DataScenarios --content-paths "/*"'